development:
  adapter: postgresql
  database: echo_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: echo_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: echo_production
  pool: 5
  timeout: 5000